### ISSUE TITLE
Error when performing dose comparison

### ISSUE THREAD

**Issue by Haydnspass** [adityaapte/CERR#12]
I always get the error shown below when I want to plot Dose Line Profiles and compare the dose of difference dose Cubes. Any hints?

 `Error using histc
Edge vector must be monotonically non-decreasing.
Error in finterp3 (line 74)
    [jnk,binIndex] = histc(zInterpV,zFieldV);
Error in getDoseAt (line 55)
dosesV = finterp3(xV, yV, zV, dA, [xVD(1)-delta xVD(2)-xVD(1)
xVD(end)+delta], [yVD(1)+delta yVD(2)-yVD(1) yVD(end)-delta], zVD, 0);
Error in doseProfileFigure (line 435)
            dV{i} = getDoseAt(doseNum, xV1, yV1, zV1, planC);
Error in doseProfileFigure (line 344)
        doseProfileFigure('refresh'); 
Error while evaluating UIControl Callback`

**Comment by adityaapte** [comment]
it look like your x/y grid values that get passed to histc are in reverse order. This might happen if dose delta x/y are not stored according to convention.

**Comment by Haydnspass** [comment]
Yes you are right! It was the zValues in the opposite order but as the array corresponded the distribution itself which has been displayed was right.
However, is there a general overview over conventions in CERR?

**Comment by adityaapte** [comment]
CERR was originally written to follow the RTOG convention.
http://itc.wustl.edu/exchange_files/tapeexch400.htm
