### ISSUE TITLE
Dead link to compiled binaries

### ISSUE THREAD

**Issue by BendigoPhysics** [adityaapte/CERR#8]
When I clicked on the link on the Wiki here to download binary files I got error 404 Not Found. Are compiled binaries for Windows still available.

Thanks

**Comment by adityaapte** [comment]
The compiled version has been updated to use Matlab 2015b runtime. The compiled code for Windows 7 64-bit can be downloaded at http://cerr.info/files/compiled_cerr_win7_64bit_Jun_16_2016.zip

Runtime for Matlab 2015b can be downloaded at http://www.mathworks.com/supportfiles/downloads/R2015b/deployment_files/R2015b/installers/win64/MCR_R2015b_win64_installer.exe
