### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by fedorov** [adityaapte/CERR#85]
From looking at the repository (or the CERR website), it is not clear under what license it is distributed.

Looking at some individual files, it seems like it is GNU.

It would be helpful to clarify licensing with a top-level license file. This guide might be helpful: https://help.github.com/articles/licensing-a-repository/

**Comment by fedorov** [comment]
This is where I came across GNU mention: https://github.com/adityaapte/CERR/blob/master/ML_Dicom/init_ML_DICOM.m#L18

**Comment by adityaapte** [comment]
Added the LICENSE file. Thanks!

**Comment by fedorov** [comment]
👍  thank you!
